spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bidnest
    username: bidnest
    password: bidnest123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true