spring:
  application:
    name: bidnest
  datasource:
    url: jdbc:h2:mem:bidnest
    username: sa
    password:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true